export const USERS_SERVICE = Symbol('USERS_SERVICE');
export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');

export const GOALS_SERVICE = Symbol('GOALS_SERVICE');
export const GOALS_REPOSITORY = Symbol('GOALS_REPOSITORY');

export const GOALS_COMPLETED_SERVICE = Symbol('GOALS_COMPLETED_SERVICE');
export const GOALS_COMPLETED_REPOSITORY = Symbol('GOALS_COMPLETED_REPOSITORY');

export const OAUTH_SERVICE = Symbol('OAUTH_SERVICE');

export const GITHUB_INTEGRATION = Symbol('GITHUB_INTEGRATION');

export const JWT_SERVICE = Symbol('JWT_SERVICE');
export const PRISMA_SERVICE = Symbol('PRISMA_SERVICE');
