FROM node:22.19.0-alpine

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --frozen-lockfile

COPY prisma ./
COPY . .

RUN yarn global add @nestjs/cli

EXPOSE 3000

CMD ["yarn", "start:dev"]
